# Makefile (c/cpp) — generated by :Snipmake
#
# Run options (all optional, combinable):
#   make run args="--verbose foo"
#   make run in=input.txt out=output.txt err=errors.txt
#   make run args="-n 10" in=data.txt out=result.txt err=run.log

TARGET   := app
SRCS     := $(wildcard *.cpp *.c)
CXXFLAGS := -g -Wall -Wextra -O2 -std=c++17

_ARGS := $(if $(args), $(args))
_IN   := $(if $(in),   < $(in))
_OUT  := $(if $(out),  > $(out))
_ERR  := $(if $(err),  2> $(err), 2>&1)

.PHONY: build run clean rebuild

build:
	@echo "[build] $(TARGET)"
	g++ $(CXXFLAGS) $(SRCS) -o $(TARGET)

run: build
	@echo "[run] ./$(TARGET)$(if $(args), $(args))$(if $(in), < $(in))$(if $(out), > $(out))$(if $(err), 2> $(err))"
	./$(TARGET) $(_ARGS) $(_IN) $(_OUT) $(_ERR)

clean:
	@echo "[clean]"
	rm -f $(TARGET) *.o

rebuild: clean build
