# Makefile (java) — generated by :Snipmake
#
# Run options (all optional, combinable):
#   make run args="arg1 arg2"
#   make run in=input.txt out=output.txt err=errors.txt
#   make run args="-Xmx512m" in=data.txt out=result.txt err=run.log

MAIN  := Main
SRCS  := $(wildcard *.java)

_ARGS := $(if $(args), $(args))
_IN   := $(if $(in),   < $(in))
_OUT  := $(if $(out),  > $(out))
_ERR  := $(if $(err),  2> $(err), 2>&1)

.PHONY: build run clean rebuild

build: $(SRCS:.java=.class)

%.class: %.java
	@echo "[build] $<"
	javac $<

run: build
	@echo "[run] java $(MAIN)$(if $(args), $(args))$(if $(in), < $(in))$(if $(out), > $(out))$(if $(err), 2> $(err))"
	java $(MAIN) $(_ARGS) $(_IN) $(_OUT) $(_ERR)

clean:
	@echo "[clean]"
	rm -f *.class

rebuild: clean build
