# Makefile (python) — generated by :Snipmake
#
# Run options (all optional, combinable):
#   make run args="--port 8080"
#   make run in=input.txt out=output.txt err=errors.txt
#   make run args="--debug" in=data.txt out=result.txt err=run.log

MAIN   := main.py
PYTHON := python3
VENV   := .venv

_ARGS := $(if $(args), $(args))
_IN   := $(if $(in),   < $(in))
_OUT  := $(if $(out),  > $(out))
_ERR  := $(if $(err),  2> $(err), 2>&1)

.PHONY: build run clean rebuild

build:
	@echo "[build] setting up venv"
	$(PYTHON) -m venv $(VENV)
	$(VENV)/bin/pip install -r requirements.txt 2>/dev/null || true

run:
	@echo "[run] $(MAIN)$(if $(args), $(args))$(if $(in), < $(in))$(if $(out), > $(out))$(if $(err), 2> $(err))"
	$(PYTHON) $(MAIN) $(_ARGS) $(_IN) $(_OUT) $(_ERR)

clean:
	@echo "[clean]"
	rm -rf $(VENV) __pycache__ *.pyc

rebuild: clean build
