# Makefile (rust) — generated by :Snipmake
#
# Run options (all optional, combinable):
#   make run args="--port 8080"
#   make run in=input.txt out=output.txt err=errors.txt
#   make run args="-v" in=data.txt out=result.txt err=run.log
#
# Note: args are passed to the binary via `cargo run -- <args>`.

_ARGS := $(if $(args), -- $(args))
_IN   := $(if $(in),   < $(in))
_OUT  := $(if $(out),  > $(out))
_ERR  := $(if $(err),  2> $(err), 2>&1)

.PHONY: build run clean rebuild

build:
	@echo "[build]"
	cargo build

run:
	@echo "[run] cargo run$(if $(args), -- $(args))$(if $(in), < $(in))$(if $(out), > $(out))$(if $(err), 2> $(err))"
	cargo run $(_ARGS) $(_IN) $(_OUT) $(_ERR)

clean:
	@echo "[clean]"
	cargo clean

rebuild: clean build
