# Makefile (tla) — generated by :Snipmake
#
# Targets:
#   make build                    — SANY syntax check
#   make run                      — TLC model checker (needs matching .cfg)
#   make run args="-simulate"     — pass extra flags to TLC
#   make run out=f.txt            — capture TLC output to file
#   make run err=f.txt            — capture TLC errors/warnings to file
#
# Note: TLA+ tools read .tla/.cfg directly; in= (stdin) is not applicable.

MODULE   := $(basename $(wildcard *.tla))
TLA2JAR  := ~/.local/share/tla2tools/tla2tools.jar
JAVA     := java
TLCFLAGS := -XX:+UseParallelGC -Xmx2g

_ARGS := $(if $(args), $(args))
_OUT  := $(if $(out),  > $(out))
_ERR  := $(if $(err),  2> $(err), 2>&1)

.PHONY: build run clean rebuild

build:
	@echo "[sany] $(MODULE).tla"
	$(JAVA) -cp $(TLA2JAR) tla2sany.SANY $(MODULE).tla $(_OUT) $(_ERR)

run:
	@echo "[tlc] $(MODULE).tla$(if $(args), $(args))$(if $(out), > $(out))$(if $(err), 2> $(err))"
	$(JAVA) $(TLCFLAGS) -cp $(TLA2JAR) tlc2.TLC \
	    -workers auto $(MODULE).tla -config $(MODULE).cfg $(_ARGS) $(_OUT) $(_ERR)

clean:
	@echo "[clean]"
	rm -rf states/ *.out

rebuild: clean build
