[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
option_as_alt = "Both"
opacity = 0.8
startup_mode = "Maximized"
# decorations = "None"

[general]
live_config_reload = true

